version: '3'
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Users/joemoore/Documents/General/Docker/jellyfin:/config
      - /Users/joemoore/Documents/General/Docker/jellyfin:/media
    ports:
      - 8096:8096
      - 7395:7359/udp # optional
    restart: unless-stopped
  
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /Users/joemoore/Documents/General/Docker:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=openvpn
      - OPENVPN_USER=R4aUNgVTmDDCsMDmeWBGatVh
      - OPENVPN_PASSWORD=Qd9ctfhhAanJypCw6rSYtR5T
      - TZ=Europe/London
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=8999
    volumes:
      - /Users/joemoore/Documents/General/Docker/qbittorrent:/config
      - /Users/joemoore/Documents/General/Docker/qbittorrent:/downloads
    network_mode: "container:gluetun"
    restart: unless-stopped
    